/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ZCatalog: typeof import('./src/components/ZCatalog.vue')['default']
    ZController: typeof import('./src/components/ZController.vue')['default']
    ZCorner: typeof import('./src/components/ZCorner.vue')['default']
    ZIllustration: typeof import('./src/components/ZIllustration.vue')['default']
    ZProgressBar: typeof import('./src/components/ZProgressBar.vue')['default']
  }
}
